name: docker

on:
  push:
    branches:
      - master
jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag image

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin "${{ secrets.DOCKER_REGISTRY }}"

      - name: Push image
        run: |
          VERSION="$(git describe --tags | sed 's/v//')"
          docker tag image abel0b/rust-dev:$VERSION
          docker push abel0b/rust-dev:$VERSION
